# Generated by Django 3.0.14 on 2022-10-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iidxrank', '0015_song_songid_iidxme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
