# Generated by Django 3.0.14 on 2023-04-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iidxrank', '0016_auto_20221017_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playrecord',
            name='playscore',
            field=models.IntegerField(default=0),
        ),
    ]
