# Generated by Django 3.2.25 on 2026-09-01 04:34

from django.db import migrations, models
import iidxrank.models


class Migration(migrations.Migration):

    dependencies = [
        ('iidxrank', '0019_machinestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=iidxrank.models.avatar_upload_to),
        ),
    ]
