# Generated by Django 3.2.25 on 2026-09-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iidxrank', '0020_player_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('ok', 'ok'), ('degraded', 'degraded'), ('down', 'down')], max_length=16)),
                ('latency_ms', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('checked_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-checked_at'],
                'index_together': {('target', 'checked_at')},
            },
        ),
    ]
