# Generated by Django 3.2.25 on 2026-09-01 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iidxrank', '0023_remove_unused_ranktables'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('purpose', models.CharField(choices=[('signup', 'signup'), ('change', 'change'), ('find_id', 'find_id'), ('reset_pw', 'reset_pw'), ('migrate', 'migrate')], max_length=16)),
                ('code', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_sent_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('send_count', models.IntegerField(default=1)),
                ('session_key', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'ordering': ['-created_at'],
                'index_together': {('email', 'purpose')},
            },
        ),
        migrations.CreateModel(
            name='AccountSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newrulepassed', models.BooleanField(db_index=True, default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('migrated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
