# Generated by Django 3.2.25 on 2026-09-25 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iidxrank', '0024_accountsecurity_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('web', 'web'), ('app', 'app')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('charts', models.IntegerField(default=0)),
                ('created', models.IntegerField(default=0)),
                ('improved', models.IntegerField(default=0)),
                ('unmatched', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
