# Generated by Django 3.2.25 on 2026-09-25 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iidxrank', '0025_recordsync'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpiValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lamp', models.SmallIntegerField()),
                ('mu', models.FloatField(null=True)),
                ('width', models.FloatField(null=True)),
                ('fetched_at', models.DateTimeField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpi_values', to='iidxrank.song')),
            ],
            options={
                'unique_together': {('song', 'lamp')},
            },
        ),
    ]
