# Generated by Django 3.2.25 on 2026-09-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iidxrank', '0026_cpivalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='playrecord',
            name='exscore',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
