# Generated by Django 3.2.25 on 2026-09-26 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iidxrank', '0027_playrecord_exscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='BpiValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('songtype', models.CharField(max_length=3)),
                ('level', models.SmallIntegerField()),
                ('notes', models.IntegerField()),
                ('wr', models.IntegerField(null=True)),
                ('kavg', models.IntegerField(null=True)),
                ('coef', models.FloatField(null=True)),
                ('mu', models.FloatField(null=True)),
                ('sigma', models.FloatField(null=True)),
                ('residual_var', models.FloatField(null=True)),
                ('fetched_at', models.DateTimeField()),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bpi_values', to='iidxrank.song')),
            ],
        ),
        migrations.CreateModel(
            name='BpiBest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bpi_best', to='iidxrank.player')),
            ],
        ),
    ]
