# Generated by Django 3.2.25 on 2026-09-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0005_commandrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandrun',
            name='prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='commandrun',
            name='prompt_answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='commandrun',
            name='prompt_asked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commandrun',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('running', '실행 중'), ('waiting', '입력 대기'), ('success', '성공'), ('failed', '실패')], default='pending', max_length=16),
        ),
    ]
